<?php

if (function_exists("register_field_group")) {
    register_field_group(array(
            'id' => 'acf_what-we-do',
            'title' => 'What We Do',
            'fields' => array(
                    array(
                            'key' => 'field_54edd8185f79f',
                            'label' => 'Header',
                            'name' => '',
                            'type' => 'tab',
                    ),
                    array(
                            'key' => 'field_54edd8235f7a0',
                            'label' => 'Header Image',
                            'name' => 'header_image',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54eda0483c2d3',
                            'label' => 'Definition of Digital',
                            'name' => '',
                            'type' => 'tab',
                    ),
                    array(
                            'key' => 'field_54eda49c63aef',
                            'label' => 'Definition of Digital Text',
                            'name' => 'definition_of_digital_text',
                            'type' => 'textarea',
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'formatting' => 'br',
                    ),
                    array(
                            'key' => 'field_54edd0a2bd9d3',
                            'label' => 'Definition of digital background image',
                            'name' => 'definition_of_digital_background_image',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54eda646b6fc6',
                            'label' => 'Services',
                            'name' => '',
                            'type' => 'tab',
                    ),
                    array(
                            'key' => 'field_54f43de6bac74',
                            'label' => 'Services',
                            'name' => 'services',
                            'type' => 'repeater',
                            'sub_fields' => array(
                                    array(
                                            'key' => 'field_54f43df7bac75',
                                            'label' => 'Image',
                                            'name' => 'image',
                                            'type' => 'image',
                                            'column_width' => '',
                                            'save_format' => 'id',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'all',
                                    ),
                            ),
                            'row_min' => 4,
                            'row_limit' => 4,
                            'layout' => 'table',
                            'button_label' => 'Add Service',
                    ),
                    array(
                            'key' => 'field_54ec5fb19ca1e',
                            'label' => 'Case Study',
                            'name' => '',
                            'type' => 'tab',
                    ),
                    array(
                            'key' => 'field_54ec60d45d3cd',
                            'label' => 'Case Study Image 1',
                            'name' => 'case_study_image_1',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54edab2a3a6df',
                            'label' => 'Case Study Title 1',
                            'name' => 'case_study_title_1',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54edab3b3a6e0',
                            'label' => 'Case Study Text 1',
                            'name' => 'case_study_text_1',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54edadbaa148a',
                            'label' => 'Case Study Image 2',
                            'name' => 'case_study_image_2',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54edab473a6e1',
                            'label' => 'Case Study Title 2',
                            'name' => 'case_study_title_2',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54edab543a6e2',
                            'label' => 'Case Study Text 2',
                            'name' => 'case_study_text_2',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_55005b3fe4ab4',
                            'label' => 'Case Study Text 3',
                            'name' => 'case_study_text_3',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54edadcba148b',
                            'label' => 'Case Study Image 3',
                            'name' => 'case_study_image_3',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_55002d6d845a3',
                            'label' => 'Carousel',
                            'name' => '',
                            'type' => 'tab',
                    ),
                    array(
                            'key' => 'field_55002d7a845a4',
                            'label' => 'Carousel Text',
                            'name' => 'carousel_text',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_55002ec6440ba',
                            'label' => 'Carousel',
                            'name' => 'carousel',
                            'type' => 'repeater',
                            'sub_fields' => array(
                                    array(
                                            'key' => 'field_5500303a1db77',
                                            'label' => 'C Image',
                                            'name' => 'c_image',
                                            'type' => 'image',
                                            'column_width' => '',
                                            'save_format' => 'id',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'all',
                                    ),
                            ),
                            'row_min' => 4,
                            'row_limit' => 8,
                            'layout' => 'table',
                            'button_label' => 'Add Row',
                    ),
                    array(
                            'key' => 'field_55005de102f96',
                            'label' => 'Case Studies',
                            'name' => 'case_studies',
                            'type' => 'repeater',
                            'sub_fields' => array(
                                    array(
                                            'key' => 'field_55005dee02f97',
                                            'label' => 'image',
                                            'name' => 'cs_image',
                                            'type' => 'image',
                                            'column_width' => '',
                                            'save_format' => 'id',
                                            'preview_size' => 'thumbnail',
                                            'library' => 'all',
                                    ),
                                    array(
                                            'key' => 'field_550063d5693d8',
                                            'label' => 'CS text',
                                            'name' => 'cs_text',
                                            'type' => 'text',
                                            'column_width' => '',
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'formatting' => 'html',
                                            'maxlength' => '',
                                    ),
                                    array(
                                            'key' => 'field_550063df693d9',
                                            'label' => 'CS title',
                                            'name' => 'cs_title',
                                            'type' => 'text',
                                            'column_width' => '',
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'formatting' => 'html',
                                            'maxlength' => '',
                                    ),
                                    array(
                                            'key' => 'field_5501aff56997c',
                                            'label' => 'CS link',
                                            'name' => 'cs_link',
                                            'type' => 'page_link',
                                            'column_width' => '',
                                            'post_type' => array(
                                                    0 => 'page',
                                            ),
                                            'allow_null' => 0,
                                            'multiple' => 0,
                                    ),
                            ),
                            'row_min' => '',
                            'row_limit' => '',
                            'layout' => 'table',
                            'button_label' => 'Add Row',
                    ),
                    array(
                            'key' => 'field_54ede71ea943e',
                            'label' => 'ANDAcademy Vimeo',
                            'name' => 'andacademy_vimeo',
                            'type' => 'text',
                            'instructions' => 'Paste the Vimeo video ID
	E.g 112052203',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54edf1c5e702c',
                            'label' => 'Academy Image',
                            'name' => 'academy_image',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54f490eb18e47',
                            'label' => 'Services Image 1',
                            'name' => 'services_image_1',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54f4910918e48',
                            'label' => 'Services Image 2',
                            'name' => 'services_image_2',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54f4911918e49',
                            'label' => 'Services Image 3',
                            'name' => 'services_image_3',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54f4912918e4a',
                            'label' => 'Services Image 4',
                            'name' => 'services_image_4',
                            'type' => 'image',
                            'save_format' => 'id',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                    ),
                    array(
                            'key' => 'field_54f71bf73d5e5',
                            'label' => 'Services text 1',
                            'name' => 'services_text_1',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54f71c083d5e6',
                            'label' => 'Services text 2',
                            'name' => 'services_text_2',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54f71c103d5e7',
                            'label' => 'services text 3',
                            'name' => 'services_text_3',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54f71c183d5e8',
                            'label' => 'Services Text 4',
                            'name' => 'services_text_4',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54f71d6032fcb',
                            'label' => 'Services Title 1',
                            'name' => 'services_title_1',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54f71d6d32fcc',
                            'label' => 'Services title 2',
                            'name' => 'services_title_2',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54f71d7632fcd',
                            'label' => 'Services Title 3',
                            'name' => 'services_title_3',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_54f71d7d32fce',
                            'label' => 'Services Title 4',
                            'name' => 'services_title_4',
                            'type' => 'text',
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'formatting' => 'html',
                            'maxlength' => '',
                    ),
                    array(
                            'key' => 'field_55006bb198b2d',
                            'label' => 'ANDacademy text',
                            'name' => 'andacademy_text',
                            'type' => 'textarea',
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'formatting' => 'br',
                    ),
            ),
            'location' => array(
                    array(
                            array(
                                    'param' => 'page_template',
                                    'operator' => '==',
                                    'value' => 'templates/what-we-do.php',
                                    'order_no' => 0,
                                    'group_no' => 0,
                            ),
                    ),
            ),
            'options' => array(
                    'position' => 'acf_after_title',
                    'layout' => 'default',
                    'hide_on_screen' => array(
                            0 => 'the_content',
                            1 => 'excerpt',
                            2 => 'custom_fields',
                            3 => 'discussion',
                            4 => 'comments',
                            5 => 'slug',
                            6 => 'author',
                            7 => 'format',
                            8 => 'featured_image',
                            9 => 'categories',
                            10 => 'tags',
                            11 => 'send-trackbacks',
                    ),
            ),
            'menu_order' => 0,
    ));
}